<?php
$cmsblockid = Mage::getStoreConfig('easy_tabs/customcms/tabidcms3');
if(!empty($cmsblockid)){
		echo '<div class="product-specs">'.$this->getLayout()->createBlock('cms/block')->setBlockId($cmsblockid)->toHtml().'</div>';
}
?>
<?php
//echo $this->getLayout()->getBlock('product.info.options')->toHtml(); 

$easytabsDivs = array();
$easytabsDivs = explode("<div >", $this->getLayout()->getBlock('product.info.options')->toHtml());
if($easytabsDivs[5] != '') {
echo '<div>'. $easytabsDivs[4];
echo '<div style="clear:both">&nbsp;</div>';
}
?>
